Repository ROCm/rpp, pull requests merged in 2023-11, with the labels that each got.

#213 RPP RICAP Tensor for HOST and HIP
  include/rppdefs.h
  include/rppt_tensor_effects_augmentations.h
  src/modules/cpu/host_tensor_effects_augmentations.hpp
  src/modules/cpu/kernel/ricap.hpp
  src/modules/hip/hip_tensor_effects_augmentations.hpp
  src/modules/hip/kernel/ricap.hpp
  src/modules/rppi_validate.hpp
  src/modules/rppt_tensor_color_augmentations.cpp
  src/modules/rppt_tensor_effects_augmentations.cpp
  src/modules/rppt_tensor_statistical_operations.cpp
  utilities/test_suite/HIP/Tensor_hip.cpp
  utilities/test_suite/HIP/runTests.py
  utilities/test_suite/HIP/testAllScript.sh
  utilities/test_suite/HOST/Tensor_host.cpp
  utilities/test_suite/HOST/runTests.py
  utilities/test_suite/HOST/testAllScript.sh
  utilities/test_suite/README.md
  utilities/test_suite/REFERENCE_OUTPUT/ricap/ricap_u8_Tensor_PKD3.csv
  utilities/test_suite/REFERENCE_OUTPUT/ricap/ricap_u8_Tensor_PLN1.csv
  utilities/test_suite/REFERENCE_OUTPUT/ricap/ricap_u8_Tensor_PLN3.csv
  utilities/test_suite/TEST_IMAGES/three_images_150x150_src1/1_img150x150.jpg
  utilities/test_suite/TEST_IMAGES/three_images_150x150_src1/2_img150x150.jpg
  utilities/test_suite/TEST_IMAGES/three_images_150x150_src1/3_img150x150.jpg
  utilities/test_suite/rpp_test_suite_common.h
Labels: enhancement

#248 Hot Fix - Changes for RPP ASAN, License file pkging
  .jenkins/common.groovy
  CHANGELOG.md
  CMakeLists.txt
Labels: enhancement, BugFix

#252 RPP Resize Mirror Normalize Bugfix
  src/modules/cpu/kernel/resize_mirror_normalize.hpp
  src/modules/hip/kernel/resize_mirror_normalize.hpp
Labels: BugFix

#263 Test suite upgrade 3 boost deps removal fix
  utilities/test_suite/rpp_test_suite_common.h
Labels: BugFix

#264 Kg/package
  .jenkins/common.groovy
  CMakeLists.txt
Labels: enhancement
