Repository ROCm/rpp, pull requests merged in 2023-09, with the labels that each got.

#180 RPP Tensor Gaussian Filter HIP support
  include/rppt_tensor_filter_augmentations.h
  src/include/hip/rpp_hip_common.hpp
  src/modules/hip/hip_tensor_filter_augmentations.hpp
  src/modules/hip/kernel/gaussian_filter.hpp
  src/modules/rppt_tensor_filter_augmentations.cpp
  utilities/test_suite/HIP/Tensor_hip.cpp
  utilities/test_suite/HIP/runTests.py
  utilities/test_suite/HIP/testAllScript.sh
  utilities/test_suite/HOST/runTests.py
  utilities/test_suite/HOST/testAllScript.sh
  utilities/test_suite/rpp_test_suite_common.h
Labels: New Feature

#203 Documentation - RPP Doxygen support
  include/rpp.h
  include/rppdefs.h
  include/rppt_tensor_color_augmentations.h
  include/rppt_tensor_data_exchange_operations.h
  include/rppt_tensor_effects_augmentations.h
  include/rppt_tensor_filter_augmentations.h
  include/rppt_tensor_geometric_augmentations.h
  include/rppt_tensor_morphological_operations.h
Labels: enhancement, BugFix

#211 Set target for dependabot PRs to develop
  .github/dependabot.yml
Labels: documentation, dependencies

#204 RPP HIP localThreads_x/y/z definitions removal
  src/include/hip/rpp_hip_common.hpp
  src/modules/hip/kernel/blend.hpp
  src/modules/hip/kernel/box_filter.hpp
  src/modules/hip/kernel/brightness.hpp
  src/modules/hip/kernel/color_cast.hpp
  src/modules/hip/kernel/color_to_greyscale.hpp
  src/modules/hip/kernel/color_twist.hpp
  src/modules/hip/kernel/contrast.hpp
  src/modules/hip/kernel/copy.hpp
  src/modules/hip/kernel/crop.hpp
  src/modules/hip/kernel/crop_mirror_normalize.hpp
  src/modules/hip/kernel/dilate.hpp
  src/modules/hip/kernel/erode.hpp
  src/modules/hip/kernel/exposure.hpp
  src/modules/hip/kernel/flip.hpp
  src/modules/hip/kernel/gamma_correction.hpp
  src/modules/hip/kernel/gridmask.hpp
  src/modules/hip/kernel/lut.hpp
  src/modules/hip/kernel/noise_gaussian.hpp
  src/modules/hip/kernel/noise_salt_and_pepper.hpp
  src/modules/hip/kernel/noise_shot.hpp
  src/modules/hip/kernel/non_linear_blend.hpp
  src/modules/hip/kernel/resize.hpp
  src/modules/hip/kernel/resize_crop_mirror.hpp
  src/modules/hip/kernel/resize_mirror_normalize.hpp
  src/modules/hip/kernel/spatter.hpp
  src/modules/hip/kernel/swap_channels.hpp
  src/modules/hip/kernel/warp_affine.hpp
Labels: BugFix

#206 RPP Tensor HIP kernels rename - "_tensor" to "_hip_tensor"
  src/modules/hip/kernel/blend.hpp
  src/modules/hip/kernel/box_filter.hpp
  src/modules/hip/kernel/brightness.hpp
  src/modules/hip/kernel/color_cast.hpp
  src/modules/hip/kernel/color_to_greyscale.hpp
  src/modules/hip/kernel/color_twist.hpp
  src/modules/hip/kernel/contrast.hpp
  src/modules/hip/kernel/copy.hpp
  src/modules/hip/kernel/crop.hpp
  src/modules/hip/kernel/crop_mirror_normalize.hpp
  src/modules/hip/kernel/dilate.hpp
  src/modules/hip/kernel/erode.hpp
  src/modules/hip/kernel/exposure.hpp
  src/modules/hip/kernel/flip.hpp
  src/modules/hip/kernel/gamma_correction.hpp
  src/modules/hip/kernel/gridmask.hpp
  src/modules/hip/kernel/lut.hpp
  src/modules/hip/kernel/noise_gaussian.hpp
  src/modules/hip/kernel/noise_salt_and_pepper.hpp
  src/modules/hip/kernel/noise_shot.hpp
  src/modules/hip/kernel/non_linear_blend.hpp
  src/modules/hip/kernel/resize.hpp
  src/modules/hip/kernel/resize_crop_mirror.hpp
  src/modules/hip/kernel/resize_mirror_normalize.hpp
  src/modules/hip/kernel/spatter.hpp
  src/modules/hip/kernel/swap_channels.hpp
  src/modules/hip/kernel/warp_affine.hpp
Labels: enhancement

#217 Doxygen - Infrastructure for RPP
  .Doxyfile
  .DoxygenLayout.xml
  .gitignore
  README.md
  docs/data/rocm.png
  include/rpp.h
  include/rppcore.h
  include/rppdefs.h
  include/rppi.h
  include/rppt.h
  include/rppt_tensor_color_augmentations.h
  include/rppt_tensor_data_exchange_operations.h
  include/rppt_tensor_effects_augmentations.h
  include/rppt_tensor_filter_augmentations.h
  include/rppt_tensor_geometric_augmentations.h
  include/rppt_tensor_morphological_operations.h
  include/rppt_tensor_statistical_operations.h
  include/rppversion.h
  src/modules/rppt_tensor_statistical_operations.cpp
Labels: enhancement
