Repository ROCm/rpp, pull requests merged in 2023-10, with the labels that each got.

#227 ENABLE ASAN packaging RPP
  CMakeLists.txt
Labels: enhancement

#181 RPP Tensor Water Augmentation on HOST and HIP
  include/rppt_tensor_effects_augmentations.h
  src/include/cpu/rpp_cpu_common.hpp
  src/include/cpu/rpp_cpu_simd.hpp
  src/modules/cpu/host_tensor_effects_augmentations.hpp
  src/modules/cpu/kernel/water.hpp
  src/modules/hip/hip_tensor_effects_augmentations.hpp
  src/modules/hip/kernel/water.hpp
  src/modules/rppt_tensor_effects_augmentations.cpp
  utilities/test_suite/HIP/Tensor_hip.cpp
  utilities/test_suite/HIP/runTests.py
  utilities/test_suite/HOST/Tensor_host.cpp
  utilities/test_suite/HOST/runTests.py
  utilities/test_suite/REFERENCE_OUTPUT/water/water_u8_Tensor_PKD3.csv
  utilities/test_suite/REFERENCE_OUTPUT/water/water_u8_Tensor_PLN1.csv
  utilities/test_suite/REFERENCE_OUTPUT/water/water_u8_Tensor_PLN3.csv
  utilities/test_suite/rpp_test_suite_common.h
Labels: New Feature

#231 RPP Boost Replacement
  CHANGELOG.md
  CMakeLists.txt
  README.md
  docker/rpp-on-ubuntu20.dockerfile
  docker/rpp-on-ubuntu22.dockerfile
  docs/prereq.md
  include/filesystem.h
  include/rppt_tensor_geometric_augmentations.h
  include/rppt_tensor_morphological_operations.h
  src/include/cl/rpp/util.hpp
  src/include/common/rpp/binary_cache.hpp
  src/include/common/rpp/handle.hpp
  src/include/common/rpp/handle_lock.hpp
  src/include/common/rpp/hip_build_utils.hpp
  src/include/common/rpp/kernel.hpp
  src/include/common/rpp/op_kernel_args.hpp
  src/include/common/rpp/tmp_dir.hpp
  src/include/common/rpp/write_file.hpp
  src/include/hip/rpp/hip_kernels.hpp
  src/include/hip/rpp/hipoc_program.hpp
  src/modules/CMakeLists.txt
  src/modules/binary_cache.cpp
  src/modules/cl/clhelper.cpp
  src/modules/cl/gcn_asm_utils.cpp
  src/modules/cl/handleocl.cpp
  src/modules/cl/hip_build_utils.cpp
  src/modules/cl/ocl_kernel.cpp
  src/modules/cl/temp_file.cpp
  src/modules/cl/tmp_dir.cpp
  src/modules/cl/utilocl.cpp
  src/modules/handlehost.cpp
  src/modules/hip/handlehip.cpp
  src/modules/hip/hip_build_utils.cpp
  src/modules/hip/hipoc_kernel.cpp
  src/modules/hip/hipoc_program.cpp
  src/modules/hip/tmp_dir.cpp
  src/modules/logger.cpp
  utilities/examples/brightness/CMakeLists.txt
  utilities/examples/brightness/brightness_hip.h
  utilities/rpp-performancetests/HIP_NEW/CMakeLists.txt
  utilities/rpp-performancetests/HOST_NEW/CMakeLists.txt
  utilities/rpp-performancetests/OCL_NEW/CMakeLists.txt
  utilities/rpp-unittests/HIP_NEW/CMakeLists.txt
  utilities/rpp-unittests/HOST_NEW/CMakeLists.txt
  utilities/rpp-unittests/OCL_NEW/CMakeLists.txt
  utilities/test_suite/HIP/CMakeLists.txt
  utilities/test_suite/HOST/CMakeLists.txt
  utilities/test_suite/rpp_test_suite_common.h
Labels: enhancement

#236 ROCm Path - Options Added
  CMakeLists.txt
Labels: enhancement

#235 ENABLE ASAN PACKAGING with component split dev, runtime and asan
  .jenkins/common.groovy
  CHANGELOG.md
  CMakeLists.txt
Labels: enhancement

#242 CTest - RPP Test Suite
  CMakeLists.txt
  utilities/rpp-unittests/HIP_NEW/CMakeLists.txt
  utilities/rpp-unittests/HOST_NEW/CMakeLists.txt
  utilities/rpp-unittests/OCL_NEW/CMakeLists.txt
  utilities/test_suite/CMakeLists.txt
  utilities/test_suite/HIP/CMakeLists.txt
  utilities/test_suite/HIP/Tensor_hip.cpp
  utilities/test_suite/HIP/runTests.py
  utilities/test_suite/HIP/testAllScript.sh
  utilities/test_suite/HOST/CMakeLists.txt
  utilities/test_suite/HOST/Tensor_host.cpp
  utilities/test_suite/HOST/runTests.py
  utilities/test_suite/HOST/testAllScript.sh
  utilities/test_suite/rpp_test_suite_common.h
Labels: enhancement, BugFix

#247 Find - Half added
  CMakeLists.txt
  README.md
  cmake/FindHALF.cmake
Labels: BugFix
