Repository ROCm/rpp, pull requests merged in 2023-12, with the labels that each got.

#258 RPP Tensor Audio Support - To Decibels
  include/rppt_tensor_audio_augmentations.h
  src/modules/cpu/host_tensor_audio_augmentations.hpp
  src/modules/cpu/kernel/to_decibels.hpp
  src/modules/rppt_tensor_audio_augmentations.cpp
  utilities/test_suite/CMakeLists.txt
  utilities/test_suite/HIP/Tensor_hip.cpp
  utilities/test_suite/HOST/Tensor_host.cpp
  utilities/test_suite/HOST/Tensor_host_audio.cpp
  utilities/test_suite/HOST/runAudioTests.py
  utilities/test_suite/REFERENCE_OUTPUTS_AUDIO/non_silent_region_detection/non_silent_region_detection_ref_237-126133-0020.txt
  utilities/test_suite/REFERENCE_OUTPUTS_AUDIO/non_silent_region_detection/non_silent_region_detection_ref_2830-3979-0005.txt
  utilities/test_suite/REFERENCE_OUTPUTS_AUDIO/non_silent_region_detection/non_silent_region_detection_ref_6829-68769-0045.txt
  utilities/test_suite/REFERENCE_OUTPUTS_AUDIO/to_decibels/to_decibels.bin
  utilities/test_suite/rpp_test_suite_audio.h
  utilities/test_suite/rpp_test_suite_common.h
Labels: enhancement

#270 Adding issue template
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/issue_report.yml
Labels: enhancement

#267 RPP Phase on HIP and HOST
  include/rppt_tensor_geometric_augmentations.h
  src/include/cpu/rpp_cpu_common.hpp
  src/include/cpu/rpp_cpu_simd.hpp
  src/include/hip/rpp_hip_common.hpp
  src/modules/cpu/host_tensor_geometric_augmentations.hpp
  src/modules/cpu/kernel/phase.hpp
  src/modules/hip/hip_tensor_geometric_augmentations.hpp
  src/modules/hip/kernel/phase.hpp
  src/modules/rppt_tensor_geometric_augmentations.cpp
  utilities/test_suite/HIP/Tensor_hip.cpp
  utilities/test_suite/HIP/runTests.py
  utilities/test_suite/HOST/Tensor_host.cpp
  utilities/test_suite/HOST/runTests.py
  utilities/test_suite/REFERENCE_OUTPUT/phase/phase_u8_Tensor_PKD3.csv
  utilities/test_suite/REFERENCE_OUTPUT/phase/phase_u8_Tensor_PLN1.csv
  utilities/test_suite/REFERENCE_OUTPUT/phase/phase_u8_Tensor_PLN3.csv
  utilities/test_suite/rpp_test_suite_common.h
Labels: enhancement

#259 RPP Tensor Audio Support - Pre Emphasis Filter
  include/rppdefs.h
  include/rppt_tensor_audio_augmentations.h
  src/modules/cpu/host_tensor_audio_augmentations.hpp
  src/modules/cpu/kernel/pre_emphasis_filter.hpp
  src/modules/rppt_tensor_audio_augmentations.cpp
  utilities/test_suite/HOST/Tensor_host_audio.cpp
  utilities/test_suite/HOST/runAudioTests.py
  utilities/test_suite/REFERENCE_OUTPUTS_AUDIO/pre_emphasis_filter/pre_emphasis_filter.bin
  utilities/test_suite/rpp_test_suite_audio.h
Labels: enhancement

#276 Testing - change output folder image writes, data dumps, performance result writes to CWD
  utilities/test_suite/HIP/runTests.py
  utilities/test_suite/HIP/runTests_voxel.py
  utilities/test_suite/HOST/runAudioTests.py
  utilities/test_suite/HOST/runTests.py
  utilities/test_suite/HOST/runTests_voxel.py
Labels: enhancement, BugFix

#279 Testing - Move default build folder for Tensor/Voxel/Audio tests on HOST/HIP to CWD
  utilities/test_suite/HIP/Tensor_hip.cpp
  utilities/test_suite/HIP/Tensor_voxel_hip.cpp
  utilities/test_suite/HIP/runTests.py
  utilities/test_suite/HIP/runTests_voxel.py
  utilities/test_suite/HOST/Tensor_host.cpp
  utilities/test_suite/HOST/Tensor_host_audio.cpp
  utilities/test_suite/HOST/Tensor_voxel_host.cpp
  utilities/test_suite/HOST/runAudioTests.py
  utilities/test_suite/HOST/runTests.py
  utilities/test_suite/HOST/runTests_voxel.py
  utilities/test_suite/rpp_test_suite_audio.h
  utilities/test_suite/rpp_test_suite_common.h
  utilities/test_suite/rpp_test_suite_voxel.h
Labels: enhancement

#280 macOS - FIX
  CMakeLists.txt
  utilities/test_suite/HIP/CMakeLists.txt
  utilities/test_suite/HOST/CMakeLists.txt
  utilities/test_suite/HOST/Tensor_host_audio.cpp
Labels: BugFix

#281 Test package
  CMakeLists.txt
  utilities/test_suite/CMakeLists.txt
  utilities/test_suite/HIP/CMakeLists.txt
  utilities/test_suite/HOST/CMakeLists.txt
Labels: enhancement

#283 Jenkins - Test Package Updates
  .github/CODEOWNERS
  .jenkins/common.groovy
Labels: enhancement
