Repository ROCm/rpp, pull requests merged in 2023-08, with the labels that each got.

#191 SWDEV-416168 - Add rocm-core dependency to rpp package
  CMakeLists.txt
Labels: enhancement

#194 Jenkins - Add Test
  .jenkins/common.groovy
Labels: enhancement

#197 CTest - Updates
  utilities/rpp-unittests/CMakeLists.txt
Labels: enhancement, BugFix

#199 Issue - Old Architecture Reference fix
  src/modules/hip/handlehip.cpp
  src/modules/hip/hipoc_program.cpp
Labels: enhancement, BugFix

#202 Update ReadtheDocs config
  .readthedocs.yaml
Labels: documentation, dependencies, docs-ci-only
