Repository ROCm/rpp, pull requests merged in 2024-02, with the labels that each got.

#303 Update doc codeowners
  .github/CODEOWNERS
Labels: documentation, ci:docs-only

#305 Test suite - upgrade 5 qa perf
  CMakeLists.txt
  utilities/rpp-performancetests/HOST_NEW/BatchPD_host_pkd3.cpp
  utilities/rpp-performancetests/HOST_NEW/BatchPD_host_pln1.cpp
  utilities/rpp-performancetests/HOST_NEW/BatchPD_host_pln3.cpp
  utilities/test_suite/HOST/CMakeLists.txt
  utilities/test_suite/HOST/runTests.py
  utilities/test_suite/README.md
  utilities/test_suite/TEST_IMAGES/eight_images_mixed_src1/img1024x768.jpg
  utilities/test_suite/TEST_IMAGES/eight_images_mixed_src1/img1280x720.jpg
  utilities/test_suite/TEST_IMAGES/eight_images_mixed_src1/img150x150.jpg
  utilities/test_suite/TEST_IMAGES/eight_images_mixed_src1/img1920x1080.jpg
  utilities/test_suite/TEST_IMAGES/eight_images_mixed_src1/img224x224.jpg
  utilities/test_suite/TEST_IMAGES/eight_images_mixed_src1/img256x256.jpg
  utilities/test_suite/TEST_IMAGES/eight_images_mixed_src1/img300x300.jpg
  utilities/test_suite/TEST_IMAGES/eight_images_mixed_src1/img3840x2160.jpg
Labels: enhancement

#271 RPP Color Temperature on HOST and HIP
  include/rppdefs.h
  include/rppt_tensor_color_augmentations.h
  src/include/cpu/rpp_cpu_common.hpp
  src/modules/cpu/host_tensor_color_augmentations.hpp
  src/modules/cpu/kernel/color_temperature.hpp
  src/modules/hip/hip_tensor_color_augmentations.hpp
  src/modules/hip/kernel/color_temperature.hpp
  src/modules/rppt_tensor_color_augmentations.cpp
  utilities/test_suite/HIP/Tensor_hip.cpp
  utilities/test_suite/HIP/runTests.py
  utilities/test_suite/HOST/Tensor_host.cpp
  utilities/test_suite/HOST/runTests.py
  utilities/test_suite/REFERENCE_OUTPUT/color_temperature/color_temperature_u8_Tensor.bin
  utilities/test_suite/rpp_test_suite_common.h
Labels: enhancement

#278 RPP Magnitude on HOST and HIP
  include/rppi_arithmetic_operations.h
  include/rppt_tensor_arithmetic_operations.h
  src/modules/cpu/host_tensor_arithmetic_operations.hpp
  src/modules/cpu/kernel/magnitude.hpp
  src/modules/hip/hip_tensor_arithmetic_operations.hpp
  src/modules/hip/kernel/magnitude.hpp
  src/modules/rppt_tensor_arithmetic_operations.cpp
  utilities/test_suite/HIP/Tensor_hip.cpp
  utilities/test_suite/HIP/runTests.py
  utilities/test_suite/HOST/Tensor_host.cpp
  utilities/test_suite/HOST/runTests.py
  utilities/test_suite/REFERENCE_OUTPUT/magnitude/magnitude_u8_Tensor.bin
  utilities/test_suite/rpp_test_suite_common.h
Labels: enhancement

#296 RPP Tensor Audio Support - Down Mixing
  include/rppt_tensor_audio_augmentations.h
  src/include/cpu/rpp_cpu_simd.hpp
  src/modules/cpu/host_tensor_audio_augmentations.hpp
  src/modules/cpu/kernel/down_mixing.hpp
  src/modules/rppt_tensor_audio_augmentations.cpp
  utilities/test_suite/HOST/CMakeLists.txt
  utilities/test_suite/HOST/Tensor_host_audio.cpp
  utilities/test_suite/HOST/runAudioTests.py
  utilities/test_suite/TEST_AUDIO_FILES/single_sample_multi_channel_src1/sample.wav
  utilities/test_suite/TEST_AUDIO_FILES/three_sample_multi_channel_src1/sample1.wav
  utilities/test_suite/TEST_AUDIO_FILES/three_sample_multi_channel_src1/sample2.wav
  utilities/test_suite/TEST_AUDIO_FILES/three_sample_multi_channel_src1/sample3.wav
  utilities/test_suite/rpp_test_suite_audio.h
Labels: enhancement

#307 Test Suite Bugfix
  utilities/test_suite/REFERENCE_OUTPUT/tensor_sum/tensor_sum_u8_Tensor.bin
  utilities/test_suite/rpp_test_suite_common.h
Labels: BugFix

#260 RPP Reduction - Tensor min and Tensor max on HOST and HIP
  include/rppt_tensor_statistical_operations.h
  src/include/cpu/rpp_cpu_common.hpp
  src/include/cpu/rpp_cpu_simd.hpp
  src/include/hip/rpp_hip_common.hpp
  src/modules/cpu/host_tensor_statistical_operations.hpp
  src/modules/cpu/kernel/tensor_max.hpp
  src/modules/cpu/kernel/tensor_min.hpp
  src/modules/hip/hip_tensor_statistical_operations.hpp
  src/modules/hip/kernel/tensor_max.hpp
  src/modules/hip/kernel/tensor_min.hpp
  src/modules/rppt_tensor_statistical_operations.cpp
  utilities/test_suite/HIP/Tensor_hip.cpp
  utilities/test_suite/HIP/runTests.py
  utilities/test_suite/HOST/Tensor_host.cpp
  utilities/test_suite/HOST/runTests.py
  utilities/test_suite/README.md
  utilities/test_suite/rpp_test_suite_common.h
Labels: enhancement
