Repository ROCm/rpp, pull requests merged in 2024-04, with the labels that each got.

#310 RPP Tensor Audio Support - Resample
  include/rppdefs.h
  include/rppt_tensor_audio_augmentations.h
  src/include/cpu/rpp_cpu_common.hpp
  src/modules/cpu/host_tensor_audio_augmentations.hpp
  src/modules/cpu/kernel/resample.hpp
  src/modules/rppt_tensor_audio_augmentations.cpp
  utilities/test_suite/HOST/Tensor_host_audio.cpp
  utilities/test_suite/HOST/runAudioTests.py
  utilities/test_suite/README.md
  utilities/test_suite/REFERENCE_OUTPUTS_AUDIO/resample/resample.bin
  utilities/test_suite/rpp_test_suite_audio.h
Labels: enhancement

#331 Docs - Missing input and output images for Doxygen
  docs/data/doxygenInputs/img150x150_1.png
  docs/data/doxygenInputs/input150x150x4.gif
  docs/data/doxygenOutputs/arithmetic_operations_add_scalar_150x150x4.gif
  docs/data/doxygenOutputs/arithmetic_operations_fused_multiply_add_scalar_150x150x4.gif
  docs/data/doxygenOutputs/arithmetic_operations_magnitude_img150x150.png
  docs/data/doxygenOutputs/arithmetic_operations_multiply_scalar_150x150x4.gif
  docs/data/doxygenOutputs/arithmetic_operations_subtract_scalar_150x150x4.gif
  docs/data/doxygenOutputs/color_augmentations_color_jitter_img150x150.png
  docs/data/doxygenOutputs/color_augmentations_color_temperature_img150x150.png
  docs/data/doxygenOutputs/effects_augmentations_ricap_img150x150.png
  docs/data/doxygenOutputs/effects_augmentations_vignette_img150x150.png
  docs/data/doxygenOutputs/effects_augmentations_water_img150x150.png
  docs/data/doxygenOutputs/geometric_augmentations_flip_150x150x4.gif
  docs/data/doxygenOutputs/geometric_augmentations_flip_img150x150.png
  docs/data/doxygenOutputs/geometric_augmentations_phase_img150x150.png
  docs/data/doxygenOutputs/geometric_augmentations_resize_crop_mirror_img115x115.png
  docs/data/doxygenOutputs/geometric_augmentations_resize_mirror_normalize_img115x115.png
  include/rppt_tensor_arithmetic_operations.h
  include/rppt_tensor_color_augmentations.h
  include/rppt_tensor_effects_augmentations.h
  include/rppt_tensor_geometric_augmentations.h
Labels: BugFix

#324 Scratch buffers rename for HOST and HIP
  include/rppdefs.h
  src/modules/cl/handleocl.cpp
  src/modules/cpu/kernel/down_mixing.hpp
  src/modules/handlehost.cpp
  src/modules/hip/handlehip.cpp
  src/modules/hip/kernel/gaussian_filter.hpp
  src/modules/hip/kernel/spatter.hpp
  src/modules/hip/kernel/tensor_max.hpp
  src/modules/hip/kernel/tensor_min.hpp
  src/modules/hip/kernel/tensor_sum.hpp
  src/modules/hip/kernel/warp_affine.hpp
  src/modules/rppt_tensor_effects_augmentations.cpp
  src/modules/rppt_tensor_geometric_augmentations.cpp
Labels: enhancement

#314 RPP Crop and Patch on HOST and HIP
  docs/data/doxygenOutputs/geometric_augmentations_crop_and_patch_img150x150.png
  include/rppt_tensor_geometric_augmentations.h
  src/include/hip/rpp_hip_common.hpp
  src/modules/cpu/host_tensor_geometric_augmentations.hpp
  src/modules/cpu/kernel/crop_and_patch.hpp
  src/modules/hip/hip_tensor_geometric_augmentations.hpp
  src/modules/hip/kernel/crop_and_patch.hpp
  src/modules/rppt_tensor_geometric_augmentations.cpp
  utilities/test_suite/HIP/Tensor_hip.cpp
  utilities/test_suite/HIP/runTests.py
  utilities/test_suite/HOST/Tensor_host.cpp
  utilities/test_suite/HOST/runTests.py
  utilities/test_suite/REFERENCE_OUTPUT/crop_and_patch/crop_and_patch_u8_Tensor.bin
  utilities/test_suite/rpp_test_suite_common.h
Labels: enhancement

#323 RPP Gaussian Noise Voxel Tensor on HOST and HIP
  docs/data/doxygenOutputs/effects_augmentations_gaussian_noise_150x150x4.gif
  include/rppdefs.h
  include/rppt_tensor_effects_augmentations.h
  src/include/cpu/rpp_cpu_common.hpp
  src/include/hip/rpp_hip_common.hpp
  src/modules/cpu/kernel/noise_gaussian.hpp
  src/modules/hip/kernel/noise_gaussian.hpp
  src/modules/rppt_tensor_effects_augmentations.cpp
  src/modules/rppt_tensor_geometric_augmentations.cpp
  utilities/test_suite/HIP/Tensor_voxel_hip.cpp
  utilities/test_suite/HIP/runTests_voxel.py
  utilities/test_suite/HOST/Tensor_voxel_host.cpp
  utilities/test_suite/HOST/runTests_voxel.py
  utilities/test_suite/rpp_test_suite_voxel.h
Labels: enhancement

#341 RPP - Package updates
  CMakeLists.txt
  cmake/FindHALF.cmake
Labels: enhancement, BugFix

#343 CMakeLists - Support AMD Advanced
  CMakeLists.txt
Labels: enhancement, BugFix
