Repository ROCm/rpp, pull requests merged in 2024-12, with the labels that each got.

#470 Fix test_suite outer cmake
  utilities/test_suite/CMakeLists.txt
Labels: BugFix, ci:precheckin

#478 RPP Gaussian filter HOST
  CHANGELOG.md
  CMakeLists.txt
  include/rpp_version.h
  include/rppt_tensor_filter_augmentations.h
  src/include/cpu/rpp_cpu_filter.hpp
  src/include/cpu/rpp_cpu_simd.hpp
  src/modules/cpu/host_tensor_filter_augmentations.hpp
  src/modules/cpu/kernel/gaussian_filter.hpp
  src/modules/rppt_tensor_filter_augmentations.cpp
  utilities/test_suite/HIP/Tensor_hip.cpp
  utilities/test_suite/HOST/Tensor_host.cpp
  utilities/test_suite/HOST/runTests.py
  utilities/test_suite/REFERENCE_OUTPUT/gaussian_filter/gaussian_filter_u8_Tensor_kernelSize3.bin
  utilities/test_suite/REFERENCE_OUTPUT/gaussian_filter/gaussian_filter_u8_Tensor_kernelSize5.bin
  utilities/test_suite/REFERENCE_OUTPUT/gaussian_filter/gaussian_filter_u8_Tensor_kernelSize7.bin
  utilities/test_suite/REFERENCE_OUTPUT/gaussian_filter/gaussian_filter_u8_Tensor_kernelSize9.bin
Labels: enhancement, ci:precheckin

#451 RPP Warp Perspective on HOST and HIP
  CHANGELOG.md
  docs/data/doxygenOutputs/geometric_augmentations_warp_perspective_img150x150.png
  include/rppdefs.h
  include/rppt_tensor_geometric_augmentations.h
  src/include/cpu/rpp_cpu_common.hpp
  src/include/cpu/rpp_cpu_simd.hpp
  src/modules/cpu/host_tensor_geometric_augmentations.hpp
  src/modules/cpu/kernel/warp_perspective.hpp
  src/modules/hip/hip_tensor_geometric_augmentations.hpp
  src/modules/hip/kernel/warp_perspective.hpp
  src/modules/rppt_tensor_geometric_augmentations.cpp
  utilities/test_suite/HIP/Tensor_hip.cpp
  utilities/test_suite/HIP/runTests.py
  utilities/test_suite/HOST/Tensor_host.cpp
  utilities/test_suite/HOST/runTests.py
  utilities/test_suite/common.py
  utilities/test_suite/rpp_test_suite_image.h
Labels: enhancement, ci:precheckin

#488 Package Updates and bug fixes
  CMakeLists.txt
  cmake/FindTurboJpeg.cmake
  utilities/examples/brightness/CMakeLists.txt
  utilities/rpp-performancetests/HIP_NEW/CMakeLists.txt
  utilities/rpp-unittests/HIP_NEW/CMakeLists.txt
  utilities/test_suite/CMakeLists.txt
  utilities/test_suite/HIP/CMakeLists.txt
  utilities/test_suite/HIP/Tensor_hip.cpp
Labels: enhancement, BugFix, ci:precheckin

#489 Jenkins - Fix Test
  .jenkins/common.groovy
  cmake/FindStdFilesystem.cmake
  utilities/test_suite/HIP/CMakeLists.txt
  utilities/test_suite/HOST/CMakeLists.txt
Labels: enhancement, BugFix, ci:precheckin
