Repository ROCm/rpp, pull requests merged in 2024-07, with the labels that each got.

#394 AMD Advanced - Build Flag
  CMakeLists.txt
Labels: enhancement

#391 Package - Remove package provides field from RPM and DEB package (#380)
  CMakeLists.txt
Labels: BugFix

#372 RPP Log Tensor on HOST and HIP
  include/rppt_tensor_arithmetic_operations.h
  src/include/cpu/rpp_cpu_common.hpp
  src/include/hip/rpp_hip_common.hpp
  src/modules/cpu/host_tensor_arithmetic_operations.hpp
  src/modules/cpu/kernel/log.hpp
  src/modules/hip/hip_tensor_arithmetic_operations.hpp
  src/modules/hip/kernel/log.hpp
  src/modules/rppt_tensor_arithmetic_operations.cpp
  utilities/test_suite/HIP/Tensor_misc_hip.cpp
  utilities/test_suite/HIP/runMiscTests.py
  utilities/test_suite/HOST/Tensor_misc_host.cpp
  utilities/test_suite/HOST/runMiscTests.py
  utilities/test_suite/REFERENCE_OUTPUTS_MISC/log/2d_output.bin
  utilities/test_suite/REFERENCE_OUTPUTS_MISC/log/3d_output.bin
  utilities/test_suite/rpp_test_suite_misc.h
Labels: enhancement

#379 RPP Test suite - Display all cases for "--help" request
  utilities/test_suite/HIP/runMiscTests.py
  utilities/test_suite/HIP/runTests.py
  utilities/test_suite/HIP/runVoxelTests.py
  utilities/test_suite/HOST/runAudioTests.py
  utilities/test_suite/HOST/runMiscTests.py
  utilities/test_suite/HOST/runTests.py
  utilities/test_suite/HOST/runVoxelTests.py
  utilities/test_suite/common.py
Labels: enhancement, BugFix

#397 Color temperature minor bugfix
  include/rppt_tensor_color_augmentations.h
  src/modules/cpu/kernel/color_temperature.hpp
  src/modules/rppt_tensor_color_augmentations.cpp
  utilities/test_suite/HOST/Tensor_host.cpp
Labels: BugFix

#400 Fix header levels in changelog
  CHANGELOG.md
Labels: documentation, ci:docs-only

#384 RPP Jitter on HOST and HIP
  docs/data/doxygenOutputs/effects_augmentations_jitter_150x150.png
  include/rppt_tensor_effects_augmentations.h
  src/include/cpu/rpp_cpu_common.hpp
  src/include/cpu/rpp_cpu_simd.hpp
  src/include/hip/rpp_hip_common.hpp
  src/modules/cpu/host_tensor_effects_augmentations.hpp
  src/modules/cpu/kernel/jitter.hpp
  src/modules/hip/hip_tensor_effects_augmentations.hpp
  src/modules/hip/kernel/jitter.hpp
  src/modules/rppt_tensor_effects_augmentations.cpp
  utilities/test_suite/HIP/Tensor_hip.cpp
  utilities/test_suite/HIP/runTests.py
  utilities/test_suite/HOST/Tensor_host.cpp
  utilities/test_suite/HOST/runTests.py
  utilities/test_suite/rpp_test_suite_common.h
Labels: enhancement

#395 RPP Audio Support HIP - Non silent region
  include/rppdefs.h
  include/rppt_tensor_audio_augmentations.h
  src/modules/hip/handlehip.cpp
  src/modules/hip/hip_tensor_audio_augmentations.hpp
  src/modules/hip/kernel/non_silent_region_detection.hpp
  src/modules/rppt_tensor_audio_augmentations.cpp
  utilities/test_suite/CMakeLists.txt
  utilities/test_suite/HIP/CMakeLists.txt
  utilities/test_suite/HIP/Tensor_audio_hip.cpp
  utilities/test_suite/HIP/runAudioTests.py
  utilities/test_suite/HOST/Tensor_audio_host.cpp
  utilities/test_suite/common.py
  utilities/test_suite/rpp_test_suite_audio.h
Labels: enhancement

#409 Add the ROCm version for each rpp release in the changelog
  CHANGELOG.md
Labels: documentation, ci:docs-only
