Repository ROCm/rpp, pull requests merged in 2024-08, with the labels that each got.

#411 Docs - Fix broken images
  include/rppt_tensor_arithmetic_operations.h
  include/rppt_tensor_effects_augmentations.h
  include/rppt_tensor_geometric_augmentations.h
Labels: documentation, ci:docs-only

#398 RPP Audio Support HIP - To Decibels
  include/rppdefs.h
  include/rppt_tensor_audio_augmentations.h
  src/modules/hip/hip_tensor_audio_augmentations.hpp
  src/modules/hip/kernel/to_decibels.hpp
  src/modules/rppt_tensor_audio_augmentations.cpp
  utilities/test_suite/HIP/Tensor_audio_hip.cpp
  utilities/test_suite/HIP/runAudioTests.py
  utilities/test_suite/HOST/Tensor_audio_host.cpp
  utilities/test_suite/common.py
  utilities/test_suite/rpp_test_suite_audio.h
Labels: enhancement

#401 RPP Audio Support HIP - Downmixing
  include/rppt_tensor_audio_augmentations.h
  src/modules/hip/hip_tensor_audio_augmentations.hpp
  src/modules/hip/kernel/down_mixing.hpp
  src/modules/rppt_tensor_audio_augmentations.cpp
  utilities/test_suite/HIP/Tensor_audio_hip.cpp
  utilities/test_suite/HIP/runAudioTests.py
  utilities/test_suite/HOST/Tensor_audio_host.cpp
Labels: enhancement

#414 Improve compiler setup
  CMakeLists.txt
Labels: enhancement

#420 Minor gaussian noise voxel bugfix
  src/include/cpu/rpp_cpu_common.hpp
  src/modules/cpu/kernel/noise_gaussian.hpp
Labels: BugFix

#410 RPP Pixelate on HOST and HIP
  docs/data/doxygenOutputs/effects_augmentations_pixelate_img150x150.jpg
  include/rppt_tensor_effects_augmentations.h
  src/include/cpu/rpp_cpu_common.hpp
  src/include/cpu/rpp_cpu_simd.hpp
  src/modules/cpu/host_tensor_effects_augmentations.hpp
  src/modules/cpu/kernel/resize.hpp
  src/modules/hip/hip_tensor_effects_augmentations.hpp
  src/modules/hip/kernel/resize.hpp
  src/modules/rppt_tensor_effects_augmentations.cpp
  utilities/test_suite/HIP/Tensor_hip.cpp
  utilities/test_suite/HIP/runTests.py
  utilities/test_suite/HOST/Tensor_host.cpp
  utilities/test_suite/HOST/runTests.py
  utilities/test_suite/REFERENCE_OUTPUT/pixelate/pixelate_u8_Tensor.bin
  utilities/test_suite/rpp_test_suite_common.h
Labels: enhancement

#423 Update documentation requirements (bump rocm-docs-core to 1.6.2)
  docs/sphinx/requirements.in
  docs/sphinx/requirements.txt
Labels: documentation, dependencies, ci:docs-only

#402 RPP Audio Support HIP - Pre emphasis filter
  include/rppt_tensor_audio_augmentations.h
  src/modules/hip/hip_tensor_audio_augmentations.hpp
  src/modules/hip/kernel/pre_emphasis_filter.hpp
  src/modules/rppt_tensor_audio_augmentations.cpp
  utilities/test_suite/HIP/Tensor_audio_hip.cpp
  utilities/test_suite/HIP/runAudioTests.py
  utilities/test_suite/HOST/Tensor_audio_host.cpp
  utilities/test_suite/common.py
Labels: enhancement

#405 RPP Audio Support HIP - Resample
  include/rppdefs.h
  include/rppt_tensor_audio_augmentations.h
  src/include/cpu/rpp_cpu_common.hpp
  src/include/hip/rpp_hip_common.hpp
  src/modules/hip/handlehip.cpp
  src/modules/hip/hip_tensor_audio_augmentations.hpp
  src/modules/hip/kernel/normalize.hpp
  src/modules/hip/kernel/resample.hpp
  src/modules/rppt_tensor_audio_augmentations.cpp
  utilities/test_suite/HIP/Tensor_audio_hip.cpp
  utilities/test_suite/HIP/runAudioTests.py
  utilities/test_suite/HOST/Tensor_audio_host.cpp
  utilities/test_suite/common.py
  utilities/test_suite/rpp_test_suite_audio.h
Labels: enhancement

#417 Test Suite - Improve results display
  utilities/test_suite/HIP/Tensor_audio_hip.cpp
  utilities/test_suite/HIP/Tensor_hip.cpp
  utilities/test_suite/HIP/Tensor_misc_hip.cpp
  utilities/test_suite/HIP/Tensor_voxel_hip.cpp
  utilities/test_suite/HIP/runAudioTests.py
  utilities/test_suite/HIP/runMiscTests.py
  utilities/test_suite/HIP/runTests.py
  utilities/test_suite/HIP/runVoxelTests.py
  utilities/test_suite/HOST/Tensor_audio_host.cpp
  utilities/test_suite/HOST/Tensor_host.cpp
  utilities/test_suite/HOST/Tensor_misc_host.cpp
  utilities/test_suite/HOST/Tensor_voxel_host.cpp
  utilities/test_suite/HOST/runAudioTests.py
  utilities/test_suite/HOST/runMiscTests.py
  utilities/test_suite/HOST/runTests.py
  utilities/test_suite/HOST/runVoxelTests.py
  utilities/test_suite/common.py
  utilities/test_suite/rpp_test_suite_audio.h
  utilities/test_suite/rpp_test_suite_common.h
  utilities/test_suite/rpp_test_suite_voxel.h
Labels: enhancement

#432 RPP Bug Fix for pixelate HIP
  src/modules/rppt_tensor_effects_augmentations.cpp
Labels: BugFix

#435 fix broken image links
  include/rppt_tensor_effects_augmentations.h
  include/rppt_tensor_geometric_augmentations.h
Labels: documentation, ci:docs-only

#437 fix broken image links
  include/rppt_tensor_effects_augmentations.h
  include/rppt_tensor_geometric_augmentations.h
Labels: documentation, ci:docs-only

#436 fix broken image links
  include/rppt_tensor_effects_augmentations.h
  include/rppt_tensor_geometric_augmentations.h
Labels: documentation, ci:docs-only

#438 Docs fix - Match parameter name in API and Docs
  include/rppt_tensor_effects_augmentations.h
  include/rppt_tensor_geometric_augmentations.h
  include/rppt_tensor_statistical_operations.h
Labels: BugFix

#442 MIVisionX compatibility fix - Resample and preemphasis filter
  include/rpp_version.h
  include/rppdefs.h
  src/include/cpu/rpp_cpu_common.hpp
  src/modules/hip/kernel/resample.hpp
  src/modules/rppt_tensor_audio_augmentations.cpp
  utilities/test_suite/HIP/Tensor_audio_hip.cpp
  utilities/test_suite/HOST/Tensor_audio_host.cpp
  utilities/test_suite/rpp_test_suite_audio.h
Labels: BugFix, high

#439 Test Suite fix - Update augmentation maps
  utilities/test_suite/HOST/runTests.py
  utilities/test_suite/common.py
  utilities/test_suite/rpp_test_suite_common.h
  utilities/test_suite/rpp_test_suite_voxel.h
Labels: BugFix

#443 ROCm 6.3.0 - updates
  CHANGELOG.md
  CMakeLists.txt
  README.md
  include/rpp_version.h
Labels: enhancement

#444 Test Suite - Minor bugfix
  utilities/test_suite/common.py
Labels: BugFix

#445 fix for Palamida scan failures
  src/modules/cpu/kernel/bitwise_and.hpp
  src/modules/cpu/kernel/bitwise_or.hpp
  src/modules/hip/kernel/bitwise_and.hpp
  src/modules/hip/kernel/bitwise_or.hpp
Labels: BugFix
