Repository ROCm/rpp, pull requests merged in 2024-11, with the labels that each got.

#466 updated the changelog for 6.3
  CHANGELOG.md
Labels: documentation, ci:docs-only

#460 added link to documentation
  README.md
Labels: documentation, ci:docs-only

#461 RPP Docs Fix
  docs/data/doxygenOutputs/effects_augmentations_jitter_img150x150.png
  docs/data/doxygenOutputs/effects_augmentations_pixelate_img150x150.png
  include/rppt_tensor_effects_augmentations.h
Labels: BugFix, ci:docs-only

#472 Readme - updates
  README.md
  docs/install/install.rst
Labels: enhancement, ci:docs-only

#471 CMakeLists - GPU Compile updates
  CMakeLists.txt
Labels: enhancement, ci:precheckin

#480 Compiler - updates and cleanup
  CHANGELOG.md
  CMakeLists.txt
  README.md
  docs/install/install.rst
  utilities/examples/brightness/CMakeLists.txt
  utilities/rpp-performancetests/HIP_NEW/CMakeLists.txt
  utilities/rpp-performancetests/HOST_NEW/CMakeLists.txt
  utilities/rpp-performancetests/OCL_NEW/CMakeLists.txt
  utilities/rpp-unittests/CMakeLists.txt
  utilities/rpp-unittests/HIP_NEW/CMakeLists.txt
  utilities/rpp-unittests/HOST_NEW/CMakeLists.txt
  utilities/rpp-unittests/OCL_NEW/CMakeLists.txt
  utilities/test_suite/CMakeLists.txt
  utilities/test_suite/HIP/CMakeLists.txt
  utilities/test_suite/HOST/CMakeLists.txt
Labels: enhancement, BugFix, ci:precheckin

#459 Restructure half.hpp and hip_fp16.h includes
  include/rppdefs.h
  src/include/cl/rpp_cl_common.hpp
  src/include/cpu/rpp_cpu_common.hpp
  src/include/cpu/rpp_cpu_simd.hpp
  src/include/hip/rpp_hip_common.hpp
  src/modules/hip/kernel/color_twist.cpp
  src/modules/hip/kernel/crop.cpp
  src/modules/hip/kernel/crop_mirror_normalize.cpp
  src/modules/hip/kernel/resize.cpp
  src/modules/hip/kernel/rotate.cpp
  src/modules/hip/kernel/warp_affine.cpp
  src/modules/rppt_tensor_arithmetic_operations.cpp
  src/modules/rppt_tensor_color_augmentations.cpp
  src/modules/rppt_tensor_data_exchange_operations.cpp
  src/modules/rppt_tensor_effects_augmentations.cpp
  src/modules/rppt_tensor_filter_augmentations.cpp
  src/modules/rppt_tensor_geometric_augmentations.cpp
  src/modules/rppt_tensor_logical_operations.cpp
  src/modules/rppt_tensor_morphological_operations.cpp
  src/modules/rppt_tensor_statistical_operations.cpp
  utilities/test_suite/HIP/Tensor_hip.cpp
  utilities/test_suite/HOST/Tensor_host.cpp
  utilities/test_suite/rpp_test_suite_image.h
Labels: enhancement, ci:precheckin
