Repository ROCm/rpp, pull requests merged in 2024-01, with the labels that each got.

#286 ROCm 6.1 updates
  .jenkins/common.groovy
  CMakeLists.txt
  README.md
  docker/rpp-on-ubuntu20.dockerfile
  docker/rpp-on-ubuntu22.dockerfile
  docs/data/AMD_RPP_logo.png
  docs/mivisionx.md
  docs/release.md
  docs/tech_support.md
  utilities/test_suite/README.md
Labels: enhancement, BugFix

#289 Use custom rocm-docs-core footer, header, and stylesheets for doxysphinx
  docs/doxygen/Doxyfile
Labels: documentation, ci:docs-only

#295 Build fix for ROCm 6.0.0 gfx942
  CMakeLists.txt
  src/modules/hip/kernel/histogram.cpp
Labels: BugFix, high

#299 RPP test_suite README update
  utilities/test_suite/README.md
Labels: enhancement
