Repository ROCm/rpp, pull requests merged in 2025-08, with the labels that each got.

#589 OpenMP - Updates
  CMakeLists.txt
  utilities/examples/brightness/CMakeLists.txt
  utilities/rpp-performancetests/HIP_NEW/CMakeLists.txt
  utilities/rpp-performancetests/HOST_NEW/CMakeLists.txt
  utilities/rpp-performancetests/OCL_NEW/CMakeLists.txt
  utilities/rpp-unittests/HIP_NEW/CMakeLists.txt
  utilities/rpp-unittests/HOST_NEW/CMakeLists.txt
  utilities/rpp-unittests/OCL_NEW/CMakeLists.txt
  utilities/test_suite/CMakeLists.txt
  utilities/test_suite/HIP/CMakeLists.txt
  utilities/test_suite/HOST/CMakeLists.txt
Labels: enhancement, BugFix, ci:precheckin

#592 CMAKE_CXX_FLAGS - remove c++ 17 flag
  CMakeLists.txt
  utilities/examples/brightness/CMakeLists.txt
  utilities/rpp-performancetests/HIP_NEW/CMakeLists.txt
  utilities/rpp-performancetests/HOST_NEW/CMakeLists.txt
  utilities/rpp-performancetests/OCL_NEW/CMakeLists.txt
  utilities/rpp-unittests/HIP_NEW/CMakeLists.txt
  utilities/rpp-unittests/HOST_NEW/CMakeLists.txt
  utilities/rpp-unittests/OCL_NEW/CMakeLists.txt
  utilities/test_suite/HIP/CMakeLists.txt
  utilities/test_suite/HOST/CMakeLists.txt
Labels: BugFix, ci:precheckin

#596 Find RPP - standardize include files
  utilities/test_suite/CMakeLists.txt
  utilities/test_suite/HIP/CMakeLists.txt
  utilities/test_suite/HOST/CMakeLists.txt
Labels: enhancement, BugFix, ci:precheckin

#559 Median Filter on HOST and HIP
  api/rppdefs.h
  api/rppt_tensor_filter_augmentations.h
  docs/data/doxygenOutputs/filter_augmentations_median_filter_kSize3_img150x150.png
  docs/data/doxygenOutputs/filter_augmentations_median_filter_kSize5_img150x150.png
  docs/data/doxygenOutputs/filter_augmentations_median_filter_kSize7_img150x150.png
  docs/data/doxygenOutputs/filter_augmentations_median_filter_kSize9_img150x150.png
  src/include/common/hip/rpp_hip_load_store.hpp
  src/include/common/hip/rpp_hip_math.hpp
  src/include/tensor/hip_tensor_executors.hpp
  src/include/tensor/host_tensor_executors.hpp
  src/modules/tensor/cpu/kernel/median_filter.cpp
  src/modules/tensor/hip/kernel/median_filter.cpp
  src/modules/tensor/rppt_tensor_filter_augmentations.cpp
  utilities/test_suite/HIP/Tensor_image_hip.cpp
  utilities/test_suite/HIP/runImageTests.py
  utilities/test_suite/HOST/Tensor_image_host.cpp
  utilities/test_suite/HOST/runImageTests.py
  utilities/test_suite/REFERENCE_OUTPUT/median_filter/median_filter_u8_Tensor_kernelSize3.bin
  utilities/test_suite/REFERENCE_OUTPUT/median_filter/median_filter_u8_Tensor_kernelSize5.bin
  utilities/test_suite/REFERENCE_OUTPUT/median_filter/median_filter_u8_Tensor_kernelSize7.bin
  utilities/test_suite/REFERENCE_OUTPUT/median_filter/median_filter_u8_Tensor_kernelSize9.bin
  utilities/test_suite/common.py
  utilities/test_suite/rpp_test_suite_image.h
Labels: enhancement, ci:precheckin

#578 Test suite - Add QA pass/fail tests for F32 bit depth
  src/modules/tensor/cpu/kernel/color_temperature.cpp
  src/modules/tensor/cpu/kernel/flip.cpp
  src/modules/tensor/cpu/kernel/glitch.cpp
  src/modules/tensor/hip/kernel/color_temperature.cpp
  utilities/test_suite/HIP/runImageTests.py
  utilities/test_suite/HOST/runImageTests.py
  utilities/test_suite/REFERENCE_OUTPUT/color_temperature/color_temperature_f32_Tensor.bin
  utilities/test_suite/REFERENCE_OUTPUT/color_to_greyscale/color_to_greyscale_f32_Tensor.bin
  utilities/test_suite/REFERENCE_OUTPUT/flip/flip_f32_Tensor.bin
  utilities/test_suite/REFERENCE_OUTPUT/glitch/glitch_f32_Tensor.bin
  utilities/test_suite/REFERENCE_OUTPUT/gridmask/gridmask_f32_Tensor.bin
  utilities/test_suite/REFERENCE_OUTPUT/non_linear_blend/non_linear_blend_f32_Tensor.bin
  utilities/test_suite/REFERENCE_OUTPUT/remap/remap_f32_Tensor_interpolationTypeBilinear.bin
  utilities/test_suite/REFERENCE_OUTPUT/remap/remap_f32_Tensor_interpolationTypeNearestNeighbor.bin
  utilities/test_suite/REFERENCE_OUTPUT/ricap/ricap_f32_Tensor.bin
Labels: ci:precheckin

#598 Jonatluu/lintian
  CMakeLists.txt
Labels: enhancement, ci:precheckin

#594 Bugfix - Rocm7.0 HIP vector types init
  src/include/common/hip/rpp_hip_interpolation.hpp
  src/include/common/hip/rpp_hip_load_store.hpp
  src/include/common/hip/rpp_hip_math.hpp
  src/include/common/hip/rpp_hip_random.hpp
  src/modules/tensor/hip/kernel/add_scalar.cpp
  src/modules/tensor/hip/kernel/blend.cpp
  src/modules/tensor/hip/kernel/box_filter.cpp
  src/modules/tensor/hip/kernel/brightness.cpp
  src/modules/tensor/hip/kernel/color_cast.cpp
  src/modules/tensor/hip/kernel/color_temperature.cpp
  src/modules/tensor/hip/kernel/color_to_greyscale.cpp
  src/modules/tensor/hip/kernel/color_twist.cpp
  src/modules/tensor/hip/kernel/contrast.cpp
  src/modules/tensor/hip/kernel/crop_mirror_normalize.cpp
  src/modules/tensor/hip/kernel/dilate.cpp
  src/modules/tensor/hip/kernel/down_mixing.cpp
  src/modules/tensor/hip/kernel/erode.cpp
  src/modules/tensor/hip/kernel/exposure.cpp
  src/modules/tensor/hip/kernel/fog.cpp
  src/modules/tensor/hip/kernel/gamma_correction.cpp
  src/modules/tensor/hip/kernel/gaussian_filter.cpp
  src/modules/tensor/hip/kernel/glitch.cpp
  src/modules/tensor/hip/kernel/jitter.cpp
  src/modules/tensor/hip/kernel/jpeg_compression_distortion.cpp
  src/modules/tensor/hip/kernel/lens_correction.cpp
  src/modules/tensor/hip/kernel/log.cpp
  src/modules/tensor/hip/kernel/log1p.cpp
  src/modules/tensor/hip/kernel/lut.cpp
  src/modules/tensor/hip/kernel/magnitude.cpp
  src/modules/tensor/hip/kernel/multiply_scalar.cpp
  src/modules/tensor/hip/kernel/noise_gaussian.cpp
  src/modules/tensor/hip/kernel/noise_shot.cpp
  src/modules/tensor/hip/kernel/non_linear_blend.cpp
  src/modules/tensor/hip/kernel/non_silent_region_detection.cpp
  src/modules/tensor/hip/kernel/normalize.cpp
  src/modules/tensor/hip/kernel/pre_emphasis_filter.cpp
  src/modules/tensor/hip/kernel/rain.cpp
  src/modules/tensor/hip/kernel/remap.cpp
  src/modules/tensor/hip/kernel/resample.cpp
  src/modules/tensor/hip/kernel/resize.cpp
  src/modules/tensor/hip/kernel/resize_crop_mirror.cpp
  src/modules/tensor/hip/kernel/resize_mirror_normalize.cpp
  src/modules/tensor/hip/kernel/slice.cpp
  src/modules/tensor/hip/kernel/spatter.cpp
  src/modules/tensor/hip/kernel/subtract_scalar.cpp
  src/modules/tensor/hip/kernel/tensor_stddev.cpp
  src/modules/tensor/hip/kernel/transpose.cpp
  src/modules/tensor/hip/kernel/vignette.cpp
  src/modules/tensor/hip/kernel/warp_affine.cpp
  src/modules/tensor/hip/kernel/warp_perspective.cpp
  src/modules/tensor/hip/kernel/water.cpp
Labels: BugFix, ci:precheckin
