Repository ROCm/rpp, pull requests merged in 2025-03, with the labels that each got.

#522 ROCm 6.4: Cherrypick
  CHANGELOG.md
  CMakeLists.txt
  docs/sphinx/requirements.in
  docs/sphinx/requirements.txt
  src/include/cpu/rpp_cpu_common.hpp
  src/include/cpu/rpp_cpu_filter.hpp
  src/include/cpu/rpp_cpu_simd.hpp
  src/modules/cpu/kernel/glitch.hpp
Labels: enhancement, BugFix, ci:precheckin

#524 RPP Test Suite - Bugfixes for Gaussian filter and QA test summary
  src/modules/cpu/kernel/gaussian_filter.hpp
  utilities/test_suite/HIP/runAudioTests.py
  utilities/test_suite/HIP/runImageTests.py
  utilities/test_suite/HIP/runMiscTests.py
  utilities/test_suite/HIP/runVoxelTests.py
  utilities/test_suite/HOST/runAudioTests.py
  utilities/test_suite/HOST/runImageTests.py
  utilities/test_suite/HOST/runMiscTests.py
  utilities/test_suite/HOST/runVoxelTests.py
  utilities/test_suite/common.py
  utilities/test_suite/rpp_test_suite_image.h
Labels: BugFix, ci:precheckin

#526 Added illustrative images for the variants and functionalities
  docs/index.rst
  docs/reference/rpp-supported-func-and-var-examples.rst
  docs/reference/rpp-supported-functionalities.rst
  docs/sphinx/_toc.yml.in
Labels: documentation, ci:docs-only

#518 RPP Test Suite - Turbo JPEG Package Installation
  CHANGELOG.md
  cmake/FindTurboJpeg.cmake
  utilities/test_suite/README.md
Labels: enhancement, ci:precheckin

#528 MIVisionX compatibility fix - Filesystem import updates
  api/rpp.h
  src/include/common/binary_cache.hpp
  src/include/common/tmp_dir.hpp
Labels: enhancement, BugFix, ci:precheckin

#532 Build fix on g++
  src/include/common/cpu/rpp_cpu_batchpd.hpp
  src/modules/tensor/cpu/kernel/resize.cpp
Labels: BugFix, ci:precheckin
