Repository ROCm/rpp, pull requests merged in 2025-01, with the labels that each got.

#493 Updates and Fixes - Compiler & Libs
  CMakeLists.txt
  src/modules/CMakeLists.txt
  utilities/examples/brightness/CMakeLists.txt
  utilities/rpp-performancetests/HIP_NEW/CMakeLists.txt
  utilities/rpp-performancetests/HOST_NEW/CMakeLists.txt
  utilities/rpp-performancetests/OCL_NEW/CMakeLists.txt
  utilities/rpp-unittests/HIP_NEW/CMakeLists.txt
  utilities/rpp-unittests/HOST_NEW/CMakeLists.txt
  utilities/rpp-unittests/OCL_NEW/CMakeLists.txt
  utilities/test_suite/CMakeLists.txt
  utilities/test_suite/HIP/CMakeLists.txt
  utilities/test_suite/HOST/CMakeLists.txt
Labels: enhancement, BugFix, ci:precheckin

#496 C++ 14 Removal
  utilities/examples/brightness/CMakeLists.txt
  utilities/rpp-performancetests/HIP_NEW/CMakeLists.txt
  utilities/rpp-performancetests/HOST_NEW/CMakeLists.txt
  utilities/rpp-performancetests/OCL_NEW/CMakeLists.txt
  utilities/rpp-unittests/HIP_NEW/CMakeLists.txt
  utilities/rpp-unittests/HOST_NEW/CMakeLists.txt
  utilities/rpp-unittests/OCL_NEW/CMakeLists.txt
  utilities/test_suite/HIP/CMakeLists.txt
  utilities/test_suite/HOST/CMakeLists.txt
Labels: enhancement, BugFix, ci:precheckin

#503 Readme & Package - Updates
  CMakeLists.txt
  README.md
  docs/install/install.rst
Labels: enhancement, BugFix, ci:precheckin

#469 Rename tensor tests for clarity
  utilities/test_suite/CMakeLists.txt
  utilities/test_suite/HIP/CMakeLists.txt
  utilities/test_suite/HIP/Tensor_image_hip.cpp
  utilities/test_suite/HIP/runImageTests.py
  utilities/test_suite/HOST/CMakeLists.txt
  utilities/test_suite/HOST/Tensor_audio_host.cpp
  utilities/test_suite/HOST/Tensor_image_host.cpp
  utilities/test_suite/HOST/runImageTests.py
  utilities/test_suite/README.md
Labels: ci:precheckin

#456 RPP Threshold on HOST and HIP
  CHANGELOG.md
  docs/data/doxygenOutputs/statistical_operations_threshold_img150x150.png
  include/rppt_tensor_statistical_operations.h
  src/include/cpu/rpp_cpu_common.hpp
  src/modules/cpu/host_tensor_statistical_operations.hpp
  src/modules/cpu/kernel/threshold.hpp
  src/modules/hip/hip_tensor_statistical_operations.hpp
  src/modules/hip/kernel/threshold.hpp
  src/modules/rppt_tensor_statistical_operations.cpp
  utilities/test_suite/HIP/Tensor_image_hip.cpp
  utilities/test_suite/HIP/runImageTests.py
  utilities/test_suite/HOST/Tensor_image_host.cpp
  utilities/test_suite/HOST/runImageTests.py
  utilities/test_suite/REFERENCE_OUTPUT/threshold/threshold_u8_Tensor.bin
  utilities/test_suite/common.py
  utilities/test_suite/rpp_test_suite_image.h
Labels: enhancement, ci:precheckin

#463 RPP Rain augmentation on HOST and HIP
  CHANGELOG.md
  docs/data/doxygenOutputs/effects_augmentations_rain_img640x480.png
  include/rppt_tensor_effects_augmentations.h
  src/include/cpu/rpp_cpu_common.hpp
  src/modules/cpu/host_tensor_effects_augmentations.hpp
  src/modules/cpu/kernel/rain.hpp
  src/modules/hip/hip_tensor_effects_augmentations.hpp
  src/modules/hip/kernel/rain.hpp
  src/modules/rppt_tensor_effects_augmentations.cpp
  utilities/test_suite/HIP/Tensor_image_hip.cpp
  utilities/test_suite/HIP/runImageTests.py
  utilities/test_suite/HOST/Tensor_image_host.cpp
  utilities/test_suite/HOST/runImageTests.py
  utilities/test_suite/common.py
  utilities/test_suite/rpp_test_suite_image.h
Labels: enhancement, ci:precheckin

#504 Created a more comprehensive installation from the readme information
  docs/conf.py
  docs/index.rst
  docs/install/install.rst
  docs/install/rpp-build-and-install.rst
  docs/install/rpp-install-with-installer.rst
  docs/install/rpp-install.rst
  docs/install/rpp-prerequisites.rst
  docs/install/rpp-verify-install.rst
  docs/reference/rpp-supported-functionalities.rst
  docs/sphinx/_toc.yml.in
Labels: documentation, ci:docs-only

#506 Test suite build fix - Lock to specific 'nifti_clib' commit
  .jenkins/common.groovy
  utilities/test_suite/README.md
Labels: enhancement, BugFix, ci:precheckin

#507 Test Package - Updates
  CMakeLists.txt
  utilities/test_suite/README.md
Labels: enhancement, BugFix, ci:precheckin

#483 Test suite - Error code detection and display
  utilities/test_suite/HIP/Tensor_image_hip.cpp
  utilities/test_suite/HIP/Tensor_voxel_hip.cpp
  utilities/test_suite/HIP/runAudioTests.py
  utilities/test_suite/HIP/runImageTests.py
  utilities/test_suite/HIP/runMiscTests.py
  utilities/test_suite/HIP/runVoxelTests.py
  utilities/test_suite/HOST/Tensor_image_host.cpp
  utilities/test_suite/HOST/Tensor_voxel_host.cpp
  utilities/test_suite/HOST/runAudioTests.py
  utilities/test_suite/HOST/runImageTests.py
  utilities/test_suite/HOST/runMiscTests.py
  utilities/test_suite/HOST/runVoxelTests.py
  utilities/test_suite/common.py
  utilities/test_suite/rpp_test_suite_image.h
Labels: enhancement, BugFix, ci:precheckin

#499 Test Suite - ENUMs for all augmentations to enhance test suite readability
  src/modules/cpu/kernel/phase.hpp
  src/modules/hip/kernel/resize.hpp
  utilities/test_suite/HIP/Tensor_audio_hip.cpp
  utilities/test_suite/HIP/Tensor_image_hip.cpp
  utilities/test_suite/HIP/Tensor_misc_hip.cpp
  utilities/test_suite/HIP/Tensor_voxel_hip.cpp
  utilities/test_suite/HIP/runAudioTests.py
  utilities/test_suite/HIP/runImageTests.py
  utilities/test_suite/HIP/runMiscTests.py
  utilities/test_suite/HIP/runVoxelTests.py
  utilities/test_suite/HOST/Tensor_audio_host.cpp
  utilities/test_suite/HOST/Tensor_image_host.cpp
  utilities/test_suite/HOST/Tensor_misc_host.cpp
  utilities/test_suite/HOST/Tensor_voxel_host.cpp
  utilities/test_suite/HOST/runAudioTests.py
  utilities/test_suite/HOST/runImageTests.py
  utilities/test_suite/HOST/runMiscTests.py
  utilities/test_suite/HOST/runVoxelTests.py
  utilities/test_suite/common.py
  utilities/test_suite/rpp_test_suite_audio.h
  utilities/test_suite/rpp_test_suite_image.h
  utilities/test_suite/rpp_test_suite_misc.h
  utilities/test_suite/rpp_test_suite_voxel.h
Labels: ci:precheckin

#510 Test Suite: OpenMP - Updates
  utilities/test_suite/CMakeLists.txt
  utilities/test_suite/HIP/CMakeLists.txt
  utilities/test_suite/HOST/CMakeLists.txt
Labels: enhancement, BugFix, ci:precheckin

#512 Deprecation fix - sprintf to snprintf
  src/modules/cl/handleocl.cpp
  utilities/rpp-performancetests/HIP_NEW/Tensor_hip_pkd3.cpp
  utilities/rpp-performancetests/HIP_NEW/Tensor_hip_pln1.cpp
  utilities/rpp-performancetests/HIP_NEW/Tensor_hip_pln3.cpp
  utilities/rpp-performancetests/HOST_NEW/Tensor_host_pkd3.cpp
  utilities/rpp-performancetests/HOST_NEW/Tensor_host_pln1.cpp
  utilities/rpp-performancetests/HOST_NEW/Tensor_host_pln3.cpp
  utilities/rpp-unittests/HIP_NEW/Tensor_hip_pkd3.cpp
  utilities/rpp-unittests/HIP_NEW/Tensor_hip_pln1.cpp
  utilities/rpp-unittests/HIP_NEW/Tensor_hip_pln3.cpp
  utilities/rpp-unittests/HOST_NEW/Tensor_host_pkd3.cpp
  utilities/rpp-unittests/HOST_NEW/Tensor_host_pln1.cpp
  utilities/rpp-unittests/HOST_NEW/Tensor_host_pln3.cpp
  utilities/test_suite/HIP/Tensor_image_hip.cpp
  utilities/test_suite/HIP/Tensor_misc_hip.cpp
  utilities/test_suite/HOST/Tensor_image_host.cpp
  utilities/test_suite/HOST/Tensor_misc_host.cpp
Labels: enhancement, BugFix, ci:precheckin

#464 RPP Bitwise-XOR on HOST and HIP
  CHANGELOG.md
  docs/data/doxygenOutputs/logical_operations_bitwise_xor_img150x150.png
  include/rppt_tensor_logical_operations.h
  src/include/cpu/rpp_cpu_simd.hpp
  src/include/hip/rpp_hip_common.hpp
  src/modules/cpu/host_tensor_logical_operations.hpp
  src/modules/cpu/kernel/bitwise_xor.hpp
  src/modules/hip/hip_tensor_logical_operations.hpp
  src/modules/hip/kernel/bitwise_xor.hpp
  src/modules/rppt_tensor_logical_operations.cpp
  utilities/test_suite/HIP/Tensor_image_hip.cpp
  utilities/test_suite/HIP/runImageTests.py
  utilities/test_suite/HOST/Tensor_image_host.cpp
  utilities/test_suite/REFERENCE_OUTPUT/bitwise_xor/bitwise_xor_u8_Tensor.bin
  utilities/test_suite/common.py
  utilities/test_suite/rpp_test_suite_image.h
Labels: enhancement, ci:precheckin

#508 Spolifroni amd/miscellaneous changes
  docs/index.rst
  docs/install/rpp-install.rst
  docs/install/rpp-prerequisites.rst
  docs/install/rpp-verify-install.rst
  docs/reference/rpp-api-reference.rst
  docs/reference/rpp-supported-functionalities.rst
  docs/sphinx/_toc.yml.in
Labels: documentation, ci:docs-only
