Repository ROCm/rpp, pull requests merged in 2025-06, with the labels that each got.

#557 Build Fix - RHEL8 - Explicit fs link for test suite
  utilities/test_suite/HIP/CMakeLists.txt
  utilities/test_suite/HOST/CMakeLists.txt
Labels: BugFix, ci:precheckin

#550 F16 variants - Update loads and stores to AVX2
  src/modules/tensor/cpu/kernel/color_temperature.cpp
  src/modules/tensor/cpu/kernel/color_to_greyscale.cpp
  src/modules/tensor/cpu/kernel/color_twist.cpp
  src/modules/tensor/cpu/kernel/noise_gaussian.cpp
  src/modules/tensor/cpu/kernel/noise_salt_and_pepper.cpp
  src/modules/tensor/cpu/kernel/noise_shot.cpp
  src/modules/tensor/cpu/kernel/non_linear_blend.cpp
  src/modules/tensor/cpu/kernel/phase.cpp
  utilities/test_suite/HIP/runImageTests.py
Labels: enhancement, ci:precheckin

#561 ffts license
  CMakeLists.txt
  third_party/ffts/FFTS_LICENSE
Labels: enhancement, BugFix, ci:precheckin

#568 CHANGELOG - ROCm 7 updates
  CHANGELOG.md
Labels: enhancement, ci:docs-only
