Repository ROCm/rpp, pull requests merged in 2025-07, with the labels that each got.

#580 README Update - Verify package
  README.md
Labels: enhancement, BugFix, ci:docs-only

#582 CMakeLists - Set Compiler and std
  CMakeLists.txt
  utilities/examples/brightness/CMakeLists.txt
  utilities/rpp-performancetests/HIP_NEW/CMakeLists.txt
  utilities/rpp-performancetests/HOST_NEW/CMakeLists.txt
  utilities/rpp-performancetests/OCL_NEW/CMakeLists.txt
  utilities/rpp-unittests/HIP_NEW/CMakeLists.txt
  utilities/rpp-unittests/HOST_NEW/CMakeLists.txt
  utilities/rpp-unittests/OCL_NEW/CMakeLists.txt
  utilities/test_suite/CMakeLists.txt
  utilities/test_suite/HIP/CMakeLists.txt
  utilities/test_suite/HOST/CMakeLists.txt
Labels: enhancement, ci:precheckin

#563 Docs: Add environment variable reference page
  docs/index.rst
  docs/reference/rpp-env-variables.rst
  docs/sphinx/_toc.yml.in
Labels: documentation, ci:docs-only

#583 Docs - Updates
  README.md
  utilities/rpp-unittests/CMakeLists.txt
Labels: enhancement, ci:docs-only

#581 Remove .jenkins
  .jenkins/common.groovy
  .jenkins/precheckin.groovy
Labels: ci:precheckin

#570 F16 variants - Update loads and stores to AVX2
  src/include/common/cpu/rpp_cpu_simd_load_store.hpp
  src/modules/tensor/cpu/kernel/tensor_max.cpp
  src/modules/tensor/cpu/kernel/tensor_mean.cpp
  src/modules/tensor/cpu/kernel/tensor_min.cpp
  src/modules/tensor/cpu/kernel/tensor_stddev.cpp
  src/modules/tensor/cpu/kernel/tensor_sum.cpp
Labels: enhancement, ci:precheckin

#588 License Fix
  src/modules/tensor/cpu/kernel/bitwise_not.cpp
  src/modules/tensor/cpu/kernel/bitwise_or.cpp
  src/modules/tensor/cpu/kernel/bitwise_xor.cpp
Labels: BugFix, ci:docs-only
